apiVersion: v1
kind: Service
metadata:
  name: pushgateway
  namespace: monitoring
spec:
  type: NodePort
  selector:
    app: pushgateway
  ports:
    - port: 9091
      targetPort: 9091
      nodePort: 30091