apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-webserver
  namespace: airflow
spec:
  replicas: 1
  selector:
    matchLabels:
      component: webserver
  template:
    metadata:
      labels:
        component: webserver
    spec:
      serviceAccountName: airflow-sa
      containers:
        - name: webserver
          image: airflow-etl:latest
          imagePullPolicy: Never
          envFrom:
            - configMapRef:
                name: airflow-config
          command: ["airflow", "webserver", "--host", "0.0.0.0", "--port", "8080"]
          ports:
            - containerPort: 8080