apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-scheduler
  namespace: airflow
spec:
  replicas: 1
  selector:
    matchLabels:
      component: scheduler
  template:
    metadata:
      labels:
        component: scheduler
    spec:
      serviceAccountName: airflow-sa
      initContainers:
      - name: init-db
        image: airflow-etl:latest
        imagePullPolicy: Never
        envFrom:
        - configMapRef:
            name: airflow-config
        command: ["airflow", "db", "init"]
      containers:
      - name: scheduler
        image: airflow-etl:latest
        imagePullPolicy: Never
        envFrom:
        - configMapRef:
            name: airflow-config
        command:
          - "airflow"
          - "scheduler"
        volumeMounts:
        - name: transformed 
          mountPath: /transformed
      volumes:
      - name: transformed
        persistentVolumeClaim:
          claimName: transformed-pvc
---
