apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-webserver
  namespace: airflow
spec:
  replicas: 1
  selector:
    matchLabels:
      component: webserver
  template:
    metadata:
      labels:
        component: webserver
    spec:
      containers:
      - name: webserver
        image: airflow-etl:latest
        imagePullPolicy: Never
        # Inject all AIRFLOW__* settings from the ConfigMap
        envFrom:
        - configMapRef:
            name: airflow-config
        # Let the image's ENTRYPOINT handle running "airflow webserver"
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: dags
          mountPath: /opt/airflow/dags
      volumes:
      - name: dags
        emptyDir: {}
