apiVersion: v1
kind: Secret
metadata:
  name: postgres-conn
  namespace: airflow
stringData:
  connection: |
    {
      "conn_id": "postgres_default",
      "conn_type": "postgres",
      "host": "postgres",
      "login": "etl_user",
      "password": "password",
      "schema": "etl_db",
      "port": 5432
    }
