# файл: .github/workflows/ci.yml
name: CI/CD ETL Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build extractor image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: docker/etl_extractor.Dockerfile
        push: false
        tags: etl_extractor:latest

    - name: Build transformer image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: docker/etl_transformer.Dockerfile
        push: false
        tags: etl_transformer:latest

    - name: Build loader image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: docker/etl_loader.Dockerfile
        push: false
        tags: etl_loader:latest

    - name: Set up Kind cluster
      uses: engineerd/setup-kind@v0.5.0
      with:
        name: etl
        config: |
          kind: Cluster
          apiVersion: kind.x-k8s.io/v1alpha4
          nodes:
          - role: control-plane

    - name: Load images into Kind
      run: |
        kind load docker-image etl_extractor:latest --name etl
        kind load docker-image etl_transformer:latest --name etl
        kind load docker-image etl_loader:latest --name etl

    - name: Install kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: v1.24.0

    - name: Deploy to Kind
      run: kubectl apply -f k8s/k8s_manifests.yaml
