name: CI/CD ELT Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build extractor image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: docker/etl_extractor.Dockerfile
          push: false
          tags: etl_extractor:${{ github.sha }}

      - name: Build transformer image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: docker/etl_transformer.Dockerfile
          push: false
          tags: etl_transformer:${{ github.sha }}

      - name: Set up Kind cluster
        uses: engineerd/setup-kind@v0.5.0
        with:
          name: etl
          config: |
            kind: Cluster
            apiVersion: kind.x-k8s.io/v1alpha4
            nodes:
              - role: control-plane

      - name: Load images into Kind
        run: |
          kind load docker-image etl_extractor:${{ github.sha }} --name etl
          kind load docker-image etl_transformer:${{ github.sha }} --name etl

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: v1.24.0

      - name: Deploy Namespaces
        run: |
          kubectl apply -f k8s/airflow/namespace.yaml
          kubectl apply -f k8s/database/namespace.yaml
          kubectl apply -f k8s/monitoring/namespace.yaml

      - name: Deploy Airflow components
        run: kubectl apply -f k8s/airflow/

      - name: Deploy Database components
        run: kubectl apply -f k8s/database/

      - name: Deploy Monitoring components
        run: kubectl apply -f k8s/monitoring/
